### ISSUE TITLE
Potential performance issue with toJS call in mapStateToProps

### ISSUE THREAD

**Issue by zarcode** [fatihAydinoglu/redux-example#1]
I am wondering if there is performance drawback of using toJS inside of mapStateToProps since redux docs are warning us about this: 
https://redux.js.org/docs/recipes/UsingImmutableJS.html#never-use-tojs-in-mapstatetoprops ? You use toJS in selectors which are called from mapStateToProps.

**Comment by fatihAydinoglu** [comment]
Hi @zarcode 

Thanks for your warning.
You are absolutely right. It was not a proper usage of selectors with immutable objects.

I have removed toJS calls. 
I will check this repo again when I have time for further improvements.
